### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by cacaotrade** [jhidalgoesp/cacaotrade#16]
As a cacaotrade developer i would like to be able to access the api from a browser frontend.  For this we are developing the project https://github.com/cacaotrade/cacaotrade-frontend .  
For this to be done i need to add CORS support to the project.  The frontend url and port should be added as environment variables inside the .env file.  Feel free to contact me if you need help with anything.

**Comment by atrievel** [comment]
@cacaotrade I can tackle this if no one else is. I might need more info from you, but this should be straightforward

**Comment by cacaotrade** [comment]
Nice, thanks for your help.

**Comment by atrievel** [comment]
@cacaotrade Of course.Just a few quick questions:
* Do you have any specific origins that should be allowed to access the app? Or should these be gotten through the environment/config? 
* Would you like a custom error message if an invalid origin tries to make a request? If so, what should it be?
* Should anonymous sources (like a mobile app) be allowed to access the app, or only the allowed origins?

**Comment by cacaotrade** [comment]
- Through the environment/config
- No message for now
- only allowed origins

**Comment by jhidalgoesp** [comment]
Thanks, i will be reviewing this asap.
