### ISSUE TITLE
Add pre-commit hook that runs linter

### ISSUE THREAD

**Issue by Tomekmularczyk** [jhidalgoesp/cacaotrade#23]
Since we now have eslint I propose that we add pre-commit hook that will do lint checking on staged files? What do you guys think? I will be happy to set it up.

**Comment by jhidalgoesp** [comment]
It sounds good.  The readme is currently an open issue if it is not done for when you finish this it would be nice if you created the file and just add a section "Note on Pull Requests" with a bullet point about the eslint config in use.

**Comment by jhidalgoesp** [comment]
Solved on #25
